swagger: '2.0'
info:
  title: sample
  x-ibm-name: sample
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - proxy:
          title: proxy
          version: 1.0.0
          verb: POST
          target-url: https://petstore.swagger.io/v2/store/order
    catch: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
basePath: /sample
paths:
  /:
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
      parameters:
        - name: ReqBody
          in: body
          schema:
            type: object
            example:
              id: 0
              petId: 0
              quantity: 0
              shipDate: '2023-04-07T15:11:46.956Z'
              status: placed
              complete: true
schemes:
  - https
